### ISSUE TITLE
Checkbox icons do not change

### ISSUE THREAD

**Issue by sjain-mi9** [ag-grid/ag-grid-react-example#30]
Hello, I have been trying to change the default icons used by ag-Grid, so far I have been able to change the other icons that I need, but unable to change checkbox icons. 

This code segment is a part of src/richGridExample/ColDefFactory (updated for icons). Not sure if I'm missing some part of the code or if its a bug. 

`{headerName: '#', width: 30, checkboxSelection: true, suppressSorting: true,
                suppressMenu: true, pinned: true,
				icons: {
						checkboxChecked: '<i class="fa fa-check-square" />',
						checkboxUnchecked: '<i class="fa fa-square-o" />',
						checkboxIndeterminate: '<i class="fa fa-filter" />',
					}
				},`

**Comment by seanlandsman** [comment]
Hi

Thanks for raising this - I've raised AG-649 our side to track this. We'll update this thread with updates as soon as we have any

thanks

**Comment by sjain-mi9** [comment]
@seanlandsman any expected date for resolving this bug?

**Comment by seanlandsman** [comment]
Hi - we've bumped this up to high and are planning at looking at this today

**Comment by seanlandsman** [comment]
Setting the icons on gridOptions instead of per column will do what you need

thanks
