### ISSUE TITLE
ag-Grid Inline Graphing Integration with React not working

### ISSUE THREAD

**Issue by anil1712** [ag-grid/ag-grid-react-example#31]
Hi,
I wanted to show charts and graphs in grid column just like this sample
https://www.ag-grid.com/javascript-grid-graphing/
So I tried with this 
<code>
{
                headerName: 'Close Trend',
                field: 'CloseTrends',
                width: 110,
                suppressResize: true,
                suppressSizeToFit: true,
                cellRenderer: `<HistoricalChartPanel historicalData={historicalData} graphHeight={230} graphWidth={400} />`
            }
</code>

but getting some exception like this
```
Uncaught TypeError: cellRendererFunc is not a function
```

Please let me know if am I doing something wrong

Thanks

**Comment by seanlandsman** [comment]
When using frameworks you need to use xxxxFramework - so in your case try cellRendererFramework
