### ISSUE TITLE
Seems like React Context values are not passed down

### ISSUE THREAD

**Issue by viknes-interana** [ag-grid/ag-grid-react-example#40]
I cloned this repo at version 19.1.1 and inside `PriceRenderer.jsx` tried to render `fontWeight` and I got `normal` instead of `bold`.

**Comment by noelalfonsomiranda** [comment]
Me too

**Comment by joshuaalpuerto** [comment]
Solve the issue by wrapping the `GridComponent` to a consumer

```js
<FontContext.Consumer>
 {(fontWeight) => (
    <AgGridReact
         context={{
               fontWeight
         }}
         .....
    />
}
</FontContext.Consumer>
```

And the context is available on cell renderer via `this.props.params.context.fontWeight`

Here is the [Doc](https://www.ag-grid.com/javascript-grid-context/)

It's kinda messy but this will do for now.

Hope it helps someone.

**Comment by seanlandsman** [comment]
This has been fixed and will be available in our next release 

thanks
