### ISSUE TITLE
Getting error on fresh install following readme instructions

### ISSUE THREAD

**Issue by RyanAtViceSoftware** [ag-grid/ag-grid-react-example#41]
After doing

`npm install`

`npm start`

the app opens a web page that shows the error below

```
This page isn’t working localhost didn’t send any data.
ERR_EMPTY_RESPONSE
```

**Comment by seanlandsman** [comment]
Hi @RyanAtViceSoftware - is this still an issue for you? I am currently unable to reproduce it.

If it is please let me know and I'll help resolve the problem
