### ISSUE TITLE
simple-redux-hook, simple-redux-dynamic examples broken

### ISSUE THREAD

**Issue by TylerRick** [ag-grid/ag-grid-react-example#45]
After running `npm run examples`, http://localhost:8080/rich-grid-declarative loads fine but the other examples do not:

http://localhost:8080/simple-redux-hook
```
ag-Grid: could not find matching row model for rowModelType clientSide
ag-Grid: Row Model "Client Side" not found. Please ensure the ClientSideRowModelModule is loaded using: import '@ag-grid-community/client-side-row-model';
```
and breaks with:
```
Cannot read property 'setRowData' of undefined
```
as soon as I click Populate Row Data.

![image](https://user-images.githubusercontent.com/14151/69575291-d0b46280-0f7e-11ea-8e92-24a3f7ca616c.png)

http://localhost:8080/simple-redux-dynamic has the same errors:

![image](https://user-images.githubusercontent.com/14151/69575411-078a7880-0f7f-11ea-89d1-d77330d6fe35.png)

**Comment by seanlandsman** [comment]
Thanks for reporting this - now fixed
