### ISSUE TITLE
Is it possible to sort by multiple columns?

### ISSUE THREAD

**Issue by tanjianyong** [ag-grid/ag-grid-react-example#68]
Seems I don't find any case and documents both here and ag-grid page( http://54.222.217.254/javascript-grid-header-rendering/). I can just find the example of sorting one column but I have the requirement of sorting multiple columns. Pls help to check the problem.

**Comment by StephenCooper** [comment]
Yes, its possible and you will find the docs here https://ag-grid.com/react-data-grid/row-sorting/#multi-column-sorting

**Comment by tanjianyong** [comment]
Sorry, what I mean is to sort multiple columns in customized header component. Here is the snapshot of your project. It seems just support sort by one column. How can I sort multiple columns in customized header?
![image](https://user-images.githubusercontent.com/12270225/175893484-9a3bde36-6555-4c1b-adb0-40b23cc57937.png)

**Comment by StephenCooper** [comment]
To do that you will need to use the sorting api from your custom header component.  Follow the pattern of using the api as in this example but instead of calling from a button call from your header. https://ag-grid.com/react-data-grid/row-sorting/#sorting-api

**Comment by tanjianyong** [comment]
Hi [StephenCooper](https://github.com/StephenCooper),
Thanks for your info. I know how to sort multiple columns by setting applyColumnState now.  But I've a problem whether it means I can't complete the functionality of sorting multiple rows by clicking header when I need to use customized header component ? Does it mean I can only add some other UI to complete it?
![image](https://user-images.githubusercontent.com/12270225/175914242-6b695305-6337-4329-bb0f-5a932984d6d5.png)

**Comment by tanjianyong** [comment]
Sorry for that, I know how to complete the functionality now. Thanks for your info.

![image](https://user-images.githubusercontent.com/12270225/175918866-5a818fd4-6dd6-431e-b8f1-b5965d9d390c.png)
